"""Evidence models used across SABER.

This file defines the canonical data structures for evidence collected during a
SABER mission. Evidence is the bridge between tool execution, finding validation,
and final reporting. A finding should not become verified unless it references
one or more EvidenceRecord objects.

Inputs:
    - Tool wrapper output metadata.
    - Raw stdout/stderr file paths.
    - Screenshots, exported JSON, XML, CSV, ZIP files, and report artifacts.
    - Manual analyst notes or approval records.

Outputs:
    - Normalized EvidenceRecord objects.
    - Compact evidence references for findings, agent handoffs, and reports.

Used by:
    - saber.core.evidence_store
    - saber.tools.* wrappers
    - saber.models.finding
    - saber.storage.database
    - saber.reporting exporters
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum
from pathlib import Path
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field, field_validator, model_validator

from saber.models.target import Target


class EvidenceType(StrEnum):
    """Supported SABER evidence types.

    Values:
        COMMAND_OUTPUT: Captured stdout/stderr or command execution metadata.
        TOOL_JSON: Structured JSON/JSONL output from a tool.
        TOOL_XML: Structured XML output from a tool.
        TOOL_TEXT: Plain text tool output.
        SCREENSHOT: Screenshot or image proof.
        FILE: Collected file artifact.
        REPORT_ARTIFACT: Generated report or export artifact.
        APPROVAL_RECORD: Operator approval/denial record.
        ANALYST_NOTE: Manual analyst note or interpretation.
    """

    COMMAND_OUTPUT = "command_output"
    TOOL_JSON = "tool_json"
    TOOL_XML = "tool_xml"
    TOOL_TEXT = "tool_text"
    SCREENSHOT = "screenshot"
    FILE = "file"
    REPORT_ARTIFACT = "report_artifact"
    APPROVAL_RECORD = "approval_record"
    ANALYST_NOTE = "analyst_note"


class EvidenceSource(StrEnum):
    """Source that produced an evidence record.

    Values:
        TOOL_WRAPPER: Evidence produced by a SABER tool wrapper.
        AGENT: Evidence or interpretation produced by an agent.
        OPERATOR: Evidence manually added by an operator.
        IMPORTED: Evidence imported from an external scanner or previous session.
        REPORTER: Evidence generated by report/export code.
    """

    TOOL_WRAPPER = "tool_wrapper"
    AGENT = "agent"
    OPERATOR = "operator"
    IMPORTED = "imported"
    REPORTER = "reporter"


class EvidenceSensitivity(StrEnum):
    """Sensitivity level for evidence handling and reporting.

    Values:
        PUBLIC: Safe to include in reports without special handling.
        INTERNAL: Internal assessment evidence; normal default.
        CONFIDENTIAL: Sensitive client or system information.
        SECRET: Credentials, tokens, hashes, keys, or highly sensitive data.
    """

    PUBLIC = "public"
    INTERNAL = "internal"
    CONFIDENTIAL = "confidential"
    SECRET = "secret"


class EvidenceStatus(StrEnum):
    """Verification state of an evidence record.

    Values:
        COLLECTED: Evidence has been collected but not reviewed.
        PARSED: Evidence has been parsed into structured observations.
        VERIFIED: Evidence has been reviewed and can support a verified finding.
        REJECTED: Evidence was reviewed and should not support a finding.
    """

    COLLECTED = "collected"
    PARSED = "parsed"
    VERIFIED = "verified"
    REJECTED = "rejected"


class CommandMetadata(BaseModel):
    """Metadata for a sandboxed or local command execution.

    Args:
        command: Structured command list executed by the wrapper.
        tool: Tool name, such as nmap, nuclei, or enum4linux-ng.
        return_code: Process return code if execution completed.
        started_at: UTC timestamp when execution started.
        finished_at: UTC timestamp when execution finished.
        duration_seconds: Runtime duration in seconds.
        sandboxed: Whether the command ran inside the SABER Docker sandbox.
        working_directory: Working directory used by the command.
        environment_redacted: Whether environment variables were redacted.

    Returns:
        A validated command metadata object.
    """

    command: list[str] = Field(default_factory=list)
    tool: str | None = None
    return_code: int | None = None
    started_at: datetime | None = None
    finished_at: datetime | None = None
    duration_seconds: float | None = Field(default=None, ge=0)
    sandboxed: bool = True
    working_directory: str | None = None
    environment_redacted: bool = True

    @field_validator("command")
    @classmethod
    def validate_command(cls, command: list[str]) -> list[str]:
        """Validate command arguments.

        Args:
            command: Command argument list.

        Returns:
            Command list with empty arguments removed.

        Raises:
            ValueError: If any argument contains a null byte.
        """

        normalized_command: list[str] = []
        for argument in command:
            normalized = argument.strip()
            if "\x00" in normalized:
                raise ValueError("command arguments cannot contain null bytes")
            if normalized:
                normalized_command.append(normalized)

        return normalized_command

    @model_validator(mode="after")
    def validate_time_order(self) -> CommandMetadata:
        """Validate command timestamp order.

        Returns:
            The validated CommandMetadata object.

        Raises:
            ValueError: If finished_at is before started_at.
        """

        if self.started_at and self.finished_at and self.finished_at < self.started_at:
            raise ValueError("finished_at cannot be earlier than started_at")
        return self


class EvidenceRecord(BaseModel):
    """Canonical SABER evidence record.

    Args:
        evidence_id: Stable evidence identifier. Auto-generated when omitted.
        type: Kind of evidence stored.
        source: Component that produced the evidence.
        status: Review/verification status.
        title: Short human-readable evidence title.
        description: Optional longer evidence description.
        target: Optional target this evidence applies to.
        tool_name: Optional tool that generated the evidence.
        file_path: Optional local path to raw evidence on disk.
        mime_type: Optional MIME type for file evidence.
        sha256: Optional SHA-256 hash of the evidence file/content.
        size_bytes: Optional evidence file size.
        command: Optional command execution metadata.
        content_preview: Short redacted preview safe for UI/report summaries.
        parsed_data: Optional structured parser output.
        sensitivity: Evidence sensitivity classification.
        redacted: Whether sensitive values have been redacted from preview/report use.
        created_at: UTC timestamp when the evidence record was created.
        metadata: Optional extra structured metadata.

    Returns:
        A normalized evidence object suitable for storage, finding references,
        and report generation.
    """

    evidence_id: str = Field(default_factory=lambda: f"ev_{uuid4().hex}")
    type: EvidenceType
    source: EvidenceSource = EvidenceSource.TOOL_WRAPPER
    status: EvidenceStatus = EvidenceStatus.COLLECTED
    title: str = Field(..., min_length=1)
    description: str | None = None
    target: Target | None = None
    tool_name: str | None = None
    file_path: str | None = None
    mime_type: str | None = None
    sha256: str | None = None
    size_bytes: int | None = Field(default=None, ge=0)
    command: CommandMetadata | None = None
    content_preview: str | None = None
    parsed_data: dict[str, Any] = Field(default_factory=dict)
    sensitivity: EvidenceSensitivity = EvidenceSensitivity.INTERNAL
    redacted: bool = False
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    metadata: dict[str, Any] = Field(default_factory=dict)

    @field_validator("evidence_id")
    @classmethod
    def validate_evidence_id(cls, evidence_id: str) -> str:
        """Validate and normalize an evidence ID.

        Args:
            evidence_id: Raw evidence ID.

        Returns:
            Stripped evidence ID.

        Raises:
            ValueError: If the ID is empty or contains whitespace.
        """

        normalized = evidence_id.strip()
        if not normalized:
            raise ValueError("evidence_id cannot be empty")
        if any(character.isspace() for character in normalized):
            raise ValueError("evidence_id cannot contain whitespace")
        return normalized

    @field_validator("title", "tool_name", "mime_type", mode="before")
    @classmethod
    def normalize_optional_text(cls, value: str | None) -> str | None:
        """Normalize short text fields.

        Args:
            value: Raw string or None.

        Returns:
            Stripped text, or None when empty.
        """

        if value is None:
            return None
        normalized = value.strip()
        return normalized or None

    @field_validator("description", "content_preview", mode="before")
    @classmethod
    def normalize_long_text(cls, value: str | None) -> str | None:
        """Normalize longer optional text fields.

        Args:
            value: Raw string or None.

        Returns:
            Stripped text, or None when empty.
        """

        if value is None:
            return None
        normalized = value.strip()
        return normalized or None

    @field_validator("file_path")
    @classmethod
    def normalize_file_path(cls, file_path: str | None) -> str | None:
        """Normalize an evidence file path.

        Args:
            file_path: Raw file path or None.

        Returns:
            POSIX-style path string, or None when empty.

        Raises:
            ValueError: If the path contains a null byte.
        """

        if file_path is None:
            return None

        normalized = file_path.strip()
        if not normalized:
            return None
        if "\x00" in normalized:
            raise ValueError("file_path cannot contain null bytes")

        return Path(normalized).as_posix()

    @field_validator("sha256")
    @classmethod
    def validate_sha256(cls, sha256: str | None) -> str | None:
        """Validate a SHA-256 digest string.

        Args:
            sha256: Raw hash string or None.

        Returns:
            Lowercase SHA-256 digest, or None.

        Raises:
            ValueError: If the digest is not a valid 64-character hex string.
        """

        if sha256 is None:
            return None

        normalized = sha256.strip().lower()
        if not normalized:
            return None
        valid_hex_digest = all(
            character in "0123456789abcdef" for character in normalized
        )
        if len(normalized) != 64 or not valid_hex_digest:
            raise ValueError("sha256 must be a 64-character hexadecimal string")

        return normalized

    @model_validator(mode="after")
    def validate_sensitivity_redaction(self) -> EvidenceRecord:
        """Validate sensitivity/redaction consistency.

        Returns:
            The validated EvidenceRecord object.

        Raises:
            ValueError: If secret evidence is marked safe without redaction.
        """

        if (
            self.sensitivity == EvidenceSensitivity.SECRET
            and not self.redacted
            and self.content_preview
        ):
            raise ValueError("secret evidence with content_preview must be marked redacted")

        tool_output_types = {
            EvidenceType.COMMAND_OUTPUT,
            EvidenceType.TOOL_JSON,
            EvidenceType.TOOL_XML,
        }
        has_evidence_content = self.file_path or self.content_preview or self.parsed_data
        if self.type in tool_output_types and not has_evidence_content:
            raise ValueError(
                "tool evidence requires file_path, content_preview, or parsed_data"
            )

        return self

    @property
    def has_file(self) -> bool:
        """Return whether this evidence points to a file artifact.

        Returns:
            True when file_path is populated.
        """

        return self.file_path is not None

    @property
    def is_sensitive(self) -> bool:
        """Return whether this evidence requires sensitive handling.

        Returns:
            True for confidential or secret evidence.
        """

        return self.sensitivity in {EvidenceSensitivity.CONFIDENTIAL, EvidenceSensitivity.SECRET}

    @property
    def can_support_verified_finding(self) -> bool:
        """Return whether this evidence can support a verified finding.

        Returns:
            True when status is VERIFIED.
        """

        return self.status == EvidenceStatus.VERIFIED

    def mark_parsed(self) -> EvidenceRecord:
        """Return a copy of this evidence marked as parsed.

        Returns:
            A new EvidenceRecord with status set to PARSED.
        """

        return self.model_copy(update={"status": EvidenceStatus.PARSED})

    def mark_verified(self) -> EvidenceRecord:
        """Return a copy of this evidence marked as verified.

        Returns:
            A new EvidenceRecord with status set to VERIFIED.
        """

        return self.model_copy(update={"status": EvidenceStatus.VERIFIED})

    def mark_rejected(self) -> EvidenceRecord:
        """Return a copy of this evidence marked as rejected.

        Returns:
            A new EvidenceRecord with status set to REJECTED.
        """

        return self.model_copy(update={"status": EvidenceStatus.REJECTED})

    def mark_sensitive(
        self,
        sensitivity: EvidenceSensitivity = EvidenceSensitivity.CONFIDENTIAL,
    ) -> EvidenceRecord:
        """Return a copy of this evidence with a higher sensitivity label.

        Args:
            sensitivity: Sensitivity value to apply.

        Returns:
            A new EvidenceRecord with updated sensitivity.
        """

        return self.model_copy(update={"sensitivity": sensitivity})

    def mark_redacted(self) -> EvidenceRecord:
        """Return a copy of this evidence marked as redacted.

        Returns:
            A new EvidenceRecord with redacted=True.
        """

        return self.model_copy(update={"redacted": True})

    def to_reference(self) -> dict[str, str | bool | None]:
        """Return a compact evidence reference for findings and reports.

        Returns:
            A JSON-compatible dictionary with stable identity and summary fields.
        """

        return {
            "evidence_id": self.evidence_id,
            "type": self.type.value,
            "title": self.title,
            "file_path": self.file_path,
            "sensitive": self.is_sensitive,
            "redacted": self.redacted,
            "status": self.status.value,
        }

    def to_agent_dict(self) -> dict[str, Any]:
        """Return compact evidence data safe for agent handoff.

        Returns:
            JSON-compatible evidence context without raw sensitive content.
        """

        return {
            "evidence_id": self.evidence_id,
            "type": self.type.value,
            "source": self.source.value,
            "status": self.status.value,
            "title": self.title,
            "target": self.target.to_agent_dict() if self.target else None,
            "tool_name": self.tool_name,
            "file_path": self.file_path,
            "content_preview": self.content_preview if not self.is_sensitive else None,
            "sensitivity": self.sensitivity.value,
            "redacted": self.redacted,
        }


class EvidenceBundle(BaseModel):
    """Collection of evidence records for a session, finding, or report.

    Args:
        bundle_id: Stable bundle identifier.
        title: Human-readable bundle title.
        records: Evidence records included in this bundle.
        created_at: UTC timestamp when the bundle object was created.
        metadata: Optional structured bundle metadata.

    Returns:
        A validated collection of evidence records.
    """

    bundle_id: str = Field(default_factory=lambda: f"bundle_{uuid4().hex}")
    title: str = Field(..., min_length=1)
    records: list[EvidenceRecord] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    metadata: dict[str, Any] = Field(default_factory=dict)

    @field_validator("bundle_id")
    @classmethod
    def validate_bundle_id(cls, bundle_id: str) -> str:
        """Validate and normalize a bundle ID.

        Args:
            bundle_id: Raw bundle identifier.

        Returns:
            Stripped bundle identifier.

        Raises:
            ValueError: If the identifier is empty or contains whitespace.
        """

        normalized = bundle_id.strip()
        if not normalized:
            raise ValueError("bundle_id cannot be empty")
        if any(character.isspace() for character in normalized):
            raise ValueError("bundle_id cannot contain whitespace")
        return normalized

    @property
    def verified_records(self) -> list[EvidenceRecord]:
        """Return evidence records marked verified.

        Returns:
            List of verified EvidenceRecord objects.
        """

        return [record for record in self.records if record.status == EvidenceStatus.VERIFIED]

    @property
    def sensitive_records(self) -> list[EvidenceRecord]:
        """Return evidence records requiring sensitive handling.

        Returns:
            List of confidential or secret EvidenceRecord objects.
        """

        return [record for record in self.records if record.is_sensitive]

    def add_record(self, record: EvidenceRecord) -> EvidenceBundle:
        """Return a copy of this bundle with one additional record.

        Args:
            record: EvidenceRecord to append.

        Returns:
            A new EvidenceBundle containing the added record.
        """

        return self.model_copy(update={"records": [*self.records, record]})

    def to_reference_list(self) -> list[dict[str, str | bool | None]]:
        """Return compact references for every evidence record in the bundle.

        Returns:
            List of evidence reference dictionaries.
        """

        return [record.to_reference() for record in self.records]